/*
 * Copyright 2023 Mikhail Titov
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dev.d1s.beam.daemon.util

import dev.d1s.beam.commons.LanguageCode
import dev.d1s.beam.commons.LanguageName

data class CommonLanguageCode(val code: LanguageCode, val name: LanguageName)

val CommonLanguageCodes = listOf(
    "aa" named "Afar",
    "ab" named "Abkhazian",
    "af" named "Afrikaans",
    "ak" named "Akan",
    "am" named "Amharic",
    "an" named "Aragonese",
    "ar" named "Arabic",
    "as" named "Assamese",
    "av" named "Avaric",
    "ay" named "Aymara",
    "az" named "Azerbaijani",
    "ba" named "Bashkir",
    "be" named "Belarusian",
    "bg" named "Bulgarian",
    "bh" named "Bihari languages",
    "bi" named "Bislama",
    "bm" named "Bambara",
    "bn" named "Bengali",
    "bo" named "Tibetan",
    "br" named "Breton",
    "bs" named "Bosnian",
    "ca" named "Catalan",
    "ce" named "Chechen",
    "ch" named "Chamorro",
    "co" named "Corsican",
    "cr" named "Cree",
    "cs" named "Czech",
    "cu" named "Church Slavic",
    "cv" named "Chuvash",
    "cy" named "Welsh",
    "da" named "Danish",
    "de" named "German",
    "dv" named "Divehi",
    "dz" named "Dzongkha",
    "ee" named "Ewe",
    "el" named "Greek",
    "en" named "English",
    "eo" named "Esperanto",
    "es" named "Spanish",
    "et" named "Estonian",
    "eu" named "Basque",
    "fa" named "Persian",
    "ff" named "Fulah",
    "fi" named "Finnish",
    "fj" named "Fijian",
    "fo" named "Faroese",
    "fr" named "French",
    "fy" named "Western Frisian",
    "ga" named "Irish",
    "gd" named "Gaelic",
    "gl" named "Galician",
    "gn" named "Guarani",
    "gu" named "Gujarati",
    "gv" named "Manx",
    "ha" named "Hausa",
    "he" named "Hebrew",
    "hi" named "Hindi",
    "ho" named "Hiri Motu",
    "hr" named "Croatian",
    "ht" named "Haitian",
    "hu" named "Hungarian",
    "hy" named "Armenian",
    "hz" named "Herero",
    "ia" named "Interlingua",
    "id" named "Indonesian",
    "ie" named "Interlingue",
    "ig" named "Igbo",
    "ii" named "Sichuan Yi",
    "ik" named "Inupiaq",
    "io" named "Ido",
    "is" named "Icelandic",
    "it" named "Italian",
    "iu" named "Inuktitut",
    "ja" named "Japanese",
    "jv" named "Javanese",
    "ka" named "Georgian",
    "kg" named "Kongo",
    "ki" named "Kikuyu",
    "kj" named "Kuanyama",
    "kk" named "Kazakh",
    "kl" named "Kalaallisut",
    "km" named "Central Khmer",
    "kn" named "Kannada",
    "ko" named "Korean",
    "kr" named "Kanuri",
    "ks" named "Kashmiri",
    "ku" named "Kurdish",
    "kv" named "Komi",
    "kw" named "Cornish",
    "ky" named "Kirghiz",
    "la" named "Latin",
    "lb" named "Luxembourgish",
    "lg" named "Ganda",
    "li" named "Limburgan",
    "ln" named "Lingala",
    "lo" named "Lao",
    "lt" named "Lithuanian",
    "lu" named "Luba-Katanga",
    "lv" named "Latvian",
    "mg" named "Malagasy",
    "mh" named "Marshallese",
    "mi" named "Maori",
    "mk" named "Macedonian",
    "ml" named "Malayalam",
    "mn" named "Mongolian",
    "mr" named "Marathi",
    "ms" named "Malay",
    "mt" named "Maltese",
    "my" named "Burmese",
    "na" named "Nauru",
    "nb" named "Bokmål, Norwegian",
    "nd" named "Ndebele, North",
    "ne" named "Nepali",
    "ng" named "Ndonga",
    "nl" named "Dutch",
    "nn" named "Norwegian Nynorsk",
    "no" named "Norwegian",
    "nr" named "Ndebele, South",
    "nv" named "Navajo",
    "ny" named "Chichewa",
    "oc" named "Occitan",
    "oj" named "Ojibwa",
    "om" named "Oromo",
    "or" named "Oriya",
    "os" named "Ossetian",
    "pa" named "Punjabi",
    "pi" named "Pali",
    "pl" named "Polish",
    "ps" named "Pushto",
    "pt" named "Portuguese",
    "qu" named "Quechua",
    "rm" named "Romansh",
    "rn" named "Rundi",
    "ro" named "Romanian",
    "ru" named "Russian",
    "rw" named "Kinyarwanda",
    "sa" named "Sanskrit",
    "sc" named "Sardinian",
    "sd" named "Sindhi",
    "se" named "Northern Sami",
    "sg" named "Sango",
    "si" named "Sinhala",
    "sk" named "Slovak",
    "sl" named "Slovenian",
    "sm" named "Samoan",
    "sn" named "Shona",
    "so" named "Somali",
    "sq" named "Albanian",
    "sr" named "Serbian",
    "ss" named "Swati",
    "st" named "Sotho, Southern",
    "su" named "Sundanese",
    "sv" named "Swedish",
    "sw" named "Swahili",
    "ta" named "Tamil",
    "te" named "Telugu",
    "tg" named "Tajik",
    "th" named "Thai",
    "ti" named "Tigrinya",
    "tk" named "Turkmen",
    "tl" named "Tagalog",
    "tn" named "Tswana",
    "to" named "Tonga",
    "tr" named "Turkish",
    "ts" named "Tsonga",
    "tt" named "Tatar",
    "tw" named "Twi",
    "ty" named "Tahitian",
    "ug" named "Uighur",
    "uk" named "Ukrainian",
    "ur" named "Urdu",
    "uz" named "Uzbek",
    "ve" named "Venda",
    "vi" named "Vietnamese",
    "vo" named "Volapük",
    "wa" named "Walloon",
    "wo" named "Wolof",
    "xh" named "Xhosa",
    "yi" named "Yiddish",
    "yo" named "Yoruba",
    "za" named "Zhuang",
    "zh" named "Chinese",
    "zu" named "Zulu"
)

private infix fun LanguageName.named(name: LanguageName) =
    CommonLanguageCode(this, name)