# Beam Daemon

### POST Space
POST http://localhost:8573/spaces
Content-Type: application/json

{
    "slug": "test-1",
    "metadata": {},
    "view": {
        "theme": "catppuccin-mocha",
        "icon": null,
        "favicon": null,
        "preview": null,
        "title": "Test space 1",
        "description": "Test space instance.",
        "remark": null
    }
}

### POST Root Space
POST http://localhost:8573/spaces/root
Content-Type: application/json

{
    "metadata": {},
    "view": {
        "theme": "accent-dark",
        "icon": null,
        "favicon": null,
        "preview": null,
        "title": "Test space",
        "description": "Test space instance.",
        "remark": null
    }
}

### GET Space
GET http://localhost:8573/spaces/root?language=en

### GET Spaces
GET http://localhost:8573/spaces?limit=10&offset=0

### PUT Space
PUT http://localhost:8573/spaces/test-1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "slug": "test-1",
    "metadata": {
    },
    "view": {
        "theme": "catppuccin-mocha",
        "icon": null,
        "favicon": null,
        "preview": null,
        "title": "Test space",
        "description": "${root.custom}",
        "remark": null
    }
}

### PUT Root Space
PUT http://localhost:8573/spaces/root
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "metadata": {
    },
    "view": {
        "theme": "accent-dark",
        "icon": null,
        "favicon": null,
        "preview": null,
        "title": "Test space",
        "description": "Test space instance.",
        "remark": null
    }
}

### DELETE Space
DELETE http://localhost:8573/spaces/test-1
Authorization: Bearer {{token}}

### POST Block
POST http://localhost:8573/blocks
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "index": 0,
    "size": "EXTRA_LARGE",
    "entities": [
        {
            "type": "void",
            "parameters": {
            }
        }
    ],
    "metadata": {
    },
    "spaceId": "root"
}

### GET Blocks
GET http://localhost:8573/blocks?space=root&language=ru

### PUT Block
PUT http://localhost:8573/blocks/5883fe73-29a6-46b5-9c7e-d907727bf530
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "index": 0,
    "size": "EXTRA_LARGE",
    "entities": [
        {
            "type": "space",
            "parameters": {
                "identifier": "root"
            }
        },
        {
            "type": "button-link",
            "parameters": {
                "text": "Does it work?",
                "url": "https://github.com/d1snin/beam"
            }
        }
    ],
    "metadata": {
    },
    "spaceId": "root"
}

### DELETE Block
DELETE http://localhost:8573/blocks/5989ded8-4101-4092-8c2d-443cf85bd96c
Authorization: Bearer {{token}}

### POST Translation
POST http://localhost:8573/translations?space=root
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "languageCode": "ru",
    "languageName": null,
    "default": false,
    "translations": {
        "ui.icon-alt": "Иконка пространства",
        "ui.default-title": "Beam",
        "ui.default-remark": "Running [Beam][https://github.com/d1snin/beam]",
        "ui.explore-dropdown.callout": "Обзор",
        "ui.daemon-status.connected": "Подключен к сервису.",
        "ui.daemon-status.disconnected": "Не удалось подключиться к сервису.",
        "ui.daemon-status.ms-unit": "мс",
        "ui.failure-card.not-found.icon-alt": "Иконка 404",
        "ui.failure-card.not-found.message": "Мы ничего не нашли.",
        "ui.failure-card.empty-space.icon-alt": "Иконка пустого пространства",
        "ui.failure-card.empty-space.message": "Эта страница выглядит пустой.",
        "ui.footer.message.first-part": "Работает на движке",
        "ui.footer.message.second-part": "Beam",
        "ui.footer.source-code-link.message": "Исходный код на GitHub",
        "ui.footer.source-code-link.url": "https://github.com/d1snin/beam",
        "ui.footer.language-switcher.message": "Поменять язык...",
        "ui.space-listing.message": "Другие страницы:",
        "ui.space-listing.fetch-more-button": "Загрузить больше",
        "ui.block.collapsed-content-entity.button.message": "Подробнее",
        "root.custom": "ru"
    }
}

### GET Translation
GET http://localhost:8573/translations/en?space=

### GET Resolved Translation
GET http://localhost:8573/translation?language=al&space=root

### GET Translations
GET http://localhost:8573/translations?space=test-1

### PUT Translation
PUT http://localhost:8573/translations/ru?space=root
Content-Type: application/json

{
    "languageCode": "ru",
    "languageName": null,
    "default": false,
    "translations": {
        "ui.icon-alt": "Иконка пространства",
        "ui.default-title": "Beam",
        "ui.default-remark": "Running [Beam][https://github.com/d1snin/beam]",
        "ui.explore-dropdown.callout": "Обзор",
        "ui.daemon-status.connected": "Подключен к сервису.",
        "ui.daemon-status.disconnected": "Не удалось подключиться к сервису.",
        "ui.daemon-status.ms-unit": "мс",
        "ui.failure-card.not-found.icon-alt": "Иконка 404",
        "ui.failure-card.not-found.message": "Мы ничего не нашли.",
        "ui.failure-card.empty-space.icon-alt": "Иконка пустого пространства",
        "ui.failure-card.empty-space.message": "Эта страница выглядит пустой.",
        "ui.footer.message.first-part": "Работает на движке",
        "ui.footer.message.second-part": "Beam",
        "ui.footer.source-code-link.message": "Исходный код на GitHub",
        "ui.footer.source-code-link.url": "https://github.com/d1snin/beam",
        "ui.footer.language-switcher.message": "Поменять язык...",
        "ui.space-listing.message": "Другие страницы:",
        "ui.space-listing.fetch-more-button": "Загрузить больше",
        "ui.block.collapsed-content-entity.button.message": "Подробнее",
        "root.custom": "ru"
    }
}

### DELETE Translation
DELETE http://localhost:8573/translations/ru?space=root
Authorization: Bearer {{token}}