# Beam Daemon

### POST Space
POST http://localhost:8573/api/spaces
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "slug": "test-1",
  "metadata": {},
  "view": {
    "theme": "catppuccin-mocha",
    "icon": null,
    "favicon": null,
    "preview": null,
    "title": "test",
    "description": "test",
    "remark": null
  }
}

### POST Root Space
POST http://localhost:8573/api/spaces/root
Content-Type: application/json

{
  "metadata": {},
  "view": {
    "theme": "accent-dark",
    "icon": null,
    "favicon": null,
    "preview": null,
    "title": "Test space",
    "description": "Test space instance.",
    "remark": null
  }
}

### GET Space
GET http://localhost:8573/api/spaces/917824b0-3b07-42f3-951a-dc81e30fde18?language=en

### GET Spaces
GET http://localhost:8573/api/spaces?limit=10&offset=0

### PUT Space
PUT http://localhost:8573/api/spaces/test-1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "slug": "test-1",
  "metadata": {
  },
  "view": {
    "theme": "catppuccin-mocha",
    "icon": null,
    "favicon": null,
    "preview": null,
    "title": "${test-1.title}",
    "description": "${test-1.description}",
    "remark": null
  }
}

### PUT Root Space
PUT http://localhost:8573/api/spaces/root
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "metadata": {
  },
  "view": {
    "theme": "accent-dark",
    "icon": null,
    "favicon": null,
    "preview": null,
    "title": "Test space",
    "description": "Test space instance.",
    "remark": null
  }
}

### DELETE Space
DELETE http://localhost:8573/api/spaces/test-1
Authorization: Bearer {{token}}

### POST Block
POST http://localhost:8573/api/blocks
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "row": 0,
  "index": null,
  "size": "EXTRA_LARGE",
  "entities": [
    {
      "type": "space",
      "parameters": {
        "identifier": "root"
      }
    }
  ],
  "metadata": {
  },
  "spaceId": "root"
}

### GET Blocks
GET http://localhost:8573/api/blocks?space=root&limit=20&offset=0&language=ru

### PUT Block
PUT http://localhost:8573/api/blocks/d35814a3-ab38-49bd-8a83-85d0b7d530ed
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "row": 0,
  "index": null,
  "size": "MEDIUM",
  "entities": [
    {
      "type": "void",
      "parameters": {
      }
    }
  ],
  "metadata": {
  },
  "spaceId": "root"
}

### DELETE Block
DELETE http://localhost:8573/api/blocks/5989ded8-4101-4092-8c2d-443cf85bd96c
Authorization: Bearer {{token}}

### DELETE Blocks
DELETE http://localhost:8573/api/blocks?space=root
Authorization: Bearer {{token}}

### GET Row
GET http://localhost:8573/api/rows/0?space=root

### GET Rows
GET http://localhost:8573/api/rows?space=root
ru
### PUT Row
PUT http://localhost:8573/api/rows/0?space=root
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "align": "CENTER",
  "metadata": {}
}

### POST Translation
POST http://localhost:8573/api/translations/en
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "languageName": "English",
  "default": false,
  "translations": {
    "ui.icon-alt": "Space icon",
    "ui.default-title": "Beam",
    "ui.default-remark": "Running [Beam][https://github.com/d1snin/beam] VERSION <version>",
    "ui.failure-card.not-found.icon-alt": "404 icon",
    "ui.failure-card.not-found.message": "We ended up with nothing.",
    "ui.failure-card.empty-space.icon-alt": "Empty space icon",
    "ui.failure-card.empty-space.message": "Seems like this space has no content blocks.",
    "ui.failure-card.lost-connection.icon-alt": "Lost connection icon",
    "ui.failure-card.lost-connection.message": "Server stopped responding...",
    "ui.footer.language-switcher.message": "Language...",
    "ui.space-listing.message": "Explore other spaces:",
    "ui.space-listing.fetch-more-button": "Fetch more",
    "ui.block.collapsed-content-entity.button.message": "More",
    "test-1.title": "en title",
    "test-1.description": "en description",
    "random.text": "random text emmm eeee"
  }
}

### GET Translation
GET http://localhost:8573/api/translations/en

### GET Resolved Translation
GET http://localhost:8573/api/translation/en

### GET Translations
GET http://localhost:8573/api/translations

### PUT Translation
PUT http://localhost:8573/api/translations/en
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "languageName": "English",
  "default": false,
  "translations": {
    "ui.icon-alt": "Space icon",
    "ui.default-title": "Beam",
    "ui.default-remark": "Running [Beam][https://github.com/d1snin/beam] VERSION <version>",
    "ui.failure-card.not-found.icon-alt": "404 icon",
    "ui.failure-card.not-found.message": "We ended up with nothing.",
    "ui.failure-card.empty-space.icon-alt": "Empty space icon",
    "ui.failure-card.empty-space.message": "Seems like this space has no content blocks.",
    "ui.failure-card.lost-connection.icon-alt": "Lost connection icon",
    "ui.failure-card.lost-connection.message": "Server stopped responding...",
    "ui.footer.language-switcher.message": "Language...",
    "ui.space-listing.message": "Explore other spaces:",
    "ui.space-listing.fetch-more-button": "Fetch more",
    "ui.block.collapsed-content-entity.button.message": "More",
    "test-1.title": "en title",
    "test-1.description": "en description"
  }
}

### DELETE Translation
DELETE http://localhost:8573/api/translations/ru?space=root
Authorization: Bearer {{token}}