# Test blocks

### POST Block with all available entities
POST http://localhost:8573/blocks
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "index": 0,
    "size": "EXTRA_LARGE",
    "entities": [
        {
            "type": "text",
            "parameters": {
                "alignment": "center",
                "value": "Test first-level heading",
                "heading": "h1"
            }
        },
        {
            "type": "text",
            "parameters": {
                "alignment": "center",
                "value": "Test text that goes after first-level heading"
            }
        },
        {
            "type": "text",
            "parameters": {
                "alignment": "end",
                "value": "Test second-level heading",
                "heading": "h2"
            }
        },
        {
            "type": "text",
            "parameters": {
                "alignment": "end",
                "value": "Test text that goes after second-level heading"
            }
        },
        {
            "type": "text",
            "parameters": {
                "value": "Test third-level heading",
                "heading": "h3"
            }
        },
        {
            "type": "text",
            "parameters": {
                "value": "Test text that goes after third-level heading"
            }
        },
        {
            "type": "text",
            "parameters": {
                "value": "(:star-fill:)(red) (**Styled**)(yellow) (__text__)(green) [*test*][https://ya.ru]",
                "heading": "h1"
            }
        },
        {
            "type": "text",
            "parameters": {
                "value": "[This][https://ya.ru] (text)(red) (`uses`)(green) **styled** *text* ~~because~~ %it is cool%"
            }
        },
        {
            "type": "text",
            "parameters": {
                "value": "Code block test",
                "heading": "h1"
            }
        },
        {
            "type": "text",
            "parameters": {
                "value": "```fun main() {\n    println(\"Hello, World!\")\n}```"
            }
        },
        {
            "type": "text",
            "parameters": {
                "alignment": "center",
                "value": "Collapsed entity test",
                "heading": "h1"
            }
        },
        {
            "type": "text",
            "parameters": {
                "alignment": "center",
                "value": "This text entity is collapsed.",
                "collapsed": "true"
            }
        },
        {
            "type": "text",
            "parameters": {
                "alignment": "end",
                "value": "This one too.",
                "collapsed": "true"
            }
        },
        {
            "type": "text",
            "parameters": {
                "value": "Let's spread some void space",
                "heading": "h1"
            }
        },
        {
            "type": "void",
            "parameters": {
            }
        },
        {
            "type": "text",
            "parameters": {
                "value": "Here is cat image",
                "heading": "h1"
            }
        },
        {
            "type": "image",
            "parameters": {
                "alignment": "center",
                "url": "https://img.fonwall.ru/o/70/kotenok-morda-lapyi-hvost.jpg",
                "description": "Cat image",
                "width": "50"
            }
        },
        {
            "type": "image",
            "parameters": {
                "url": "https://img.fonwall.ru/o/70/kotenok-morda-lapyi-hvost.jpg",
                "description": "Cat image",
                "width": "100"
            }
        },
        {
            "type": "text",
            "parameters": {
                "value": "Space link test",
                "heading": "h1"
            }
        },
        {
            "type": "space",
            "parameters": {
                "alignment": "center",
                "identifier": "root"
            }
        },
        {
            "type": "space",
            "parameters": {
                "identifier": "root",
                "full_width": "true"
            }
        },
        {
            "type": "text",
            "parameters": {
                "value": "Embed test",
                "heading": "h1"
            }
        },
        {
            "type": "embed",
            "parameters": {
                "alignment": "center",
                "url": "https://www.openstreetmap.org/export/embed.html?bbox=73.3026695251465%2C61.22659383317754%2C73.46660614013673%2C61.27765817597264&amp;layer=mapnik",
                "width": "50"
            }
        },
        {
            "type": "embed",
            "parameters": {
                "url": "https://www.openstreetmap.org/export/embed.html?bbox=73.3026695251465%2C61.22659383317754%2C73.46660614013673%2C61.27765817597264&amp;layer=mapnik",
                "width": "100"
            }
        },
        {
            "type": "text",
            "parameters": {
                "value": "Button link test",
                "heading": "h1"
            }
        },
        {
            "type": "button-link",
            "parameters": {
                "text": "Test button",
                "icon": "star",
                "url": "https://ya.ru",
                "width": "100"
            }
        },
        {
            "type": "button-link",
            "parameters": {
                "alignment": "center",
                "text": "Test button",
                "icon": "star",
                "url": "https://ya.ru",
                "width": "50"
            }
        },
        {
            "type": "button-link",
            "parameters": {
                "alignment": "center",
                "text": "Test button",
                "icon": "star",
                "url": "https://ya.ru",
                "style": "primary"
            }
        },
        {
            "type": "button-link",
            "parameters": {
                "alignment": "start",
                "text": "Test button",
                "icon": "star",
                "url": "https://ya.ru",
                "style": "success"
            }
        },
        {
            "type": "button-link",
            "parameters": {
                "alignment": "start",
                "text": "Test button",
                "icon": "star",
                "url": "https://ya.ru",
                "style": "danger"
            }
        },
        {
            "type": "button-link",
            "parameters": {
                "alignment": "end",
                "text": "Test button",
                "icon": "star",
                "url": "https://ya.ru",
                "style": "warning"
            }
        },
        {
            "type": "button-link",
            "parameters": {
                "alignment": "end",
                "text": "Test button",
                "icon": "star",
                "url": "https://ya.ru",
                "style": "info"
            }
        }
    ],
    "metadata": {},
    "spaceId": "root"
}