version: "3.8"

services:
  sapphire-server:
    image: sapphire-server:latest
    container_name: sapphire-server
    restart: always
    networks:
      - sapphire-net
    expose:
      - "8573"
    ports:
      - "8573:5432"
    env_file:
      - "../.env"
    depends_on:
      - sapphire-server-postgres

  sapphire-server-postgres:
    image: postgres:latest
    container_name: sapphire-server-postgres
    environment:
      - POSTGRES_DB=sapphire_database
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_password
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always
    networks:
      - sapphire-server-net
    expose:
      - "5432"
    volumes:
      - sapphire-server-db-data-postgres:/var/lib/postgresql/data
      - sapphire-server-db-data-postgres-config:/var/lib/postgresql/dataConfig

networks:
  sapphire-server-net:
    driver: bridge

volumes:
  sapphire-server-db-data-postgres:
    driver: local

  sapphire-server-db-data-postgres-config:
    driver: local